services:
  mongo:
    image: mongo:latest
    container_name: mongo_daily
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1213
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: